//Auth Types
export const LOAD = "LOAD";
export const TYPE = "TYPE";
export const KEYSTORE = "KEYSTORE";
export const METAMASK = "METAMASK";
export const XDEFI = "XDEFI";
export const WALLETCONNECT = "WALLETCONNECT";
export const REGISTER_MSG = "REGISTER_MSG";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const COINMARKETCAP_SUCCESS = "COINMARKETCAP_SUCCESS";
export const COINMARKETCAP_FAIL = "COINMARKETCAP_FAIL";
export const MIDGARDPOOL_REQUESTING = "MIDGARDPOOL_REQUESTING";
export const MIDGARDPOOL_SUCCESS = "MIDGARDPOOL_SUCCESS";
export const MIDGARDPOOL_FAIL = "MIDGARDPOOL_FAIL";
export const KEYSTORECONNECTION_REQUESTING = "KEYSTORECONNECTION_REQUESTING";
export const KEYSTORECONNECTION_SUCCESS = "KEYSTORECONNECTION_SUCCESS";
export const KEYSTORECONNECTION_FAIL = "KEYSTORECONNECTION_FAIL";
export const KEYSTORE_TRANSACTIONHISTORY_REQUESTING =
  "KEYSTORE_TRANSACTIONHISTORY_REQUESTING";
export const KEYSTORE_TRANSACTIONHISTORY_SUCCESS =
  "KEYSTORE_TRANSACTIONHISTORY_SUCCESS";
export const KEYSTORE_TRANSACTIONHISTORY_FAIL =
  "KEYSTORE_TRANSACTIONHISTORY_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_SETTINGS = "SET_SETTINGS";
export const LOGIN = "LOGIN";
export const MAINMODAL = "MAINMODAL";
export const TRANSACTION_HISTORY_MODAL = "TRANSACTION_HISTORY_MODAL";
export const SET_GRAPH_DATA = "SET_GRAPH_DATA";
